// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,14,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	DateofBirth   string                 `protobuf:"bytes,3,opt,name=dateofBirth,proto3" json:"dateofBirth,omitempty"`
	Nationality   string                 `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         int64                  `protobuf:"varint,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address1      string                 `protobuf:"bytes,7,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2      string                 `protobuf:"bytes,8,opt,name=address2,proto3" json:"address2,omitempty"`
	City          string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Country       string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	UserName      string                 `protobuf:"bytes,12,opt,name=userName,proto3" json:"userName,omitempty"`
	Password      string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateRequest) GetDateofBirth() string {
	if x != nil {
		return x.DateofBirth
	}
	return ""
}

func (x *CreateRequest) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *CreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRequest) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *CreateRequest) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *CreateRequest) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *CreateRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,14,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	DateofBirth   string                 `protobuf:"bytes,3,opt,name=dateofBirth,proto3" json:"dateofBirth,omitempty"`
	Nationality   string                 `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         int64                  `protobuf:"varint,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address1      string                 `protobuf:"bytes,7,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2      string                 `protobuf:"bytes,8,opt,name=address2,proto3" json:"address2,omitempty"`
	City          string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Country       string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	UserName      string                 `protobuf:"bytes,12,opt,name=userName,proto3" json:"userName,omitempty"`
	Password      string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	Message       string                 `protobuf:"bytes,15,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateResponse) GetDateofBirth() string {
	if x != nil {
		return x.DateofBirth
	}
	return ""
}

func (x *CreateResponse) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *CreateResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateResponse) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *CreateResponse) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *CreateResponse) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *CreateResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateResponse) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,14,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	DateofBirth   string                 `protobuf:"bytes,3,opt,name=dateofBirth,proto3" json:"dateofBirth,omitempty"`
	Nationality   string                 `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         int64                  `protobuf:"varint,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address1      string                 `protobuf:"bytes,7,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2      string                 `protobuf:"bytes,8,opt,name=address2,proto3" json:"address2,omitempty"`
	City          string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Country       string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	UserName      string                 `protobuf:"bytes,12,opt,name=userName,proto3" json:"userName,omitempty"`
	Password      string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *FindRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *FindRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *FindRequest) GetDateofBirth() string {
	if x != nil {
		return x.DateofBirth
	}
	return ""
}

func (x *FindRequest) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *FindRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FindRequest) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *FindRequest) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *FindRequest) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *FindRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *FindRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *FindRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FindRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FindRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,14,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	DateofBirth   string                 `protobuf:"bytes,3,opt,name=dateofBirth,proto3" json:"dateofBirth,omitempty"`
	Nationality   string                 `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         int64                  `protobuf:"varint,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address1      string                 `protobuf:"bytes,7,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2      string                 `protobuf:"bytes,8,opt,name=address2,proto3" json:"address2,omitempty"`
	City          string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Country       string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	UserName      string                 `protobuf:"bytes,12,opt,name=userName,proto3" json:"userName,omitempty"`
	Password      string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	Message       string                 `protobuf:"bytes,15,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *FindResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *FindResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *FindResponse) GetDateofBirth() string {
	if x != nil {
		return x.DateofBirth
	}
	return ""
}

func (x *FindResponse) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *FindResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FindResponse) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *FindResponse) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *FindResponse) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *FindResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *FindResponse) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *FindResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FindResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FindResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *FindResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_user_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1capi/helloworld/v1/user.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\x8f\x03\n" +
	"\rcreateRequest\x12\x16\n" +
	"\x06userId\x18\x0e \x01(\x03R\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12 \n" +
	"\vdateofBirth\x18\x03 \x01(\tR\vdateofBirth\x12 \n" +
	"\vnationality\x18\x04 \x01(\tR\vnationality\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\x03R\x05phone\x12\x1a\n" +
	"\baddress1\x18\a \x01(\tR\baddress1\x12\x1a\n" +
	"\baddress2\x18\b \x01(\tR\baddress2\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x1a\n" +
	"\buserName\x18\f \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\"\xaa\x03\n" +
	"\x0ecreateResponse\x12\x16\n" +
	"\x06userId\x18\x0e \x01(\x03R\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12 \n" +
	"\vdateofBirth\x18\x03 \x01(\tR\vdateofBirth\x12 \n" +
	"\vnationality\x18\x04 \x01(\tR\vnationality\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\x03R\x05phone\x12\x1a\n" +
	"\baddress1\x18\a \x01(\tR\baddress1\x12\x1a\n" +
	"\baddress2\x18\b \x01(\tR\baddress2\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x1a\n" +
	"\buserName\x18\f \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\x12\x18\n" +
	"\amessage\x18\x0f \x01(\tR\amessage\"\x8d\x03\n" +
	"\vfindRequest\x12\x16\n" +
	"\x06userId\x18\x0e \x01(\x03R\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12 \n" +
	"\vdateofBirth\x18\x03 \x01(\tR\vdateofBirth\x12 \n" +
	"\vnationality\x18\x04 \x01(\tR\vnationality\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\x03R\x05phone\x12\x1a\n" +
	"\baddress1\x18\a \x01(\tR\baddress1\x12\x1a\n" +
	"\baddress2\x18\b \x01(\tR\baddress2\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x1a\n" +
	"\buserName\x18\f \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\"\xa8\x03\n" +
	"\ffindResponse\x12\x16\n" +
	"\x06userId\x18\x0e \x01(\x03R\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12 \n" +
	"\vdateofBirth\x18\x03 \x01(\tR\vdateofBirth\x12 \n" +
	"\vnationality\x18\x04 \x01(\tR\vnationality\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\x03R\x05phone\x12\x1a\n" +
	"\baddress1\x18\a \x01(\tR\baddress1\x12\x1a\n" +
	"\baddress2\x18\b \x01(\tR\baddress2\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x1a\n" +
	"\buserName\x18\f \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\x12\x18\n" +
	"\amessage\x18\x0f \x01(\tR\amessage2\xcf\x01\n" +
	"\x04User\x12d\n" +
	"\n" +
	"CreateUser\x12\x1c.helloworld.v1.createRequest\x1a\x1d.helloworld.v1.createResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0ev1/user/create\x12a\n" +
	"\bFindUser\x12\x1a.helloworld.v1.findRequest\x1a\x1b.helloworld.v1.findResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14v1/user/find/{email}BV\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z!user-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_user_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_user_proto_rawDescData []byte
)

func file_api_helloworld_v1_user_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_user_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_user_proto_rawDesc), len(file_api_helloworld_v1_user_proto_rawDesc)))
	})
	return file_api_helloworld_v1_user_proto_rawDescData
}

var file_api_helloworld_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_helloworld_v1_user_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: helloworld.v1.createRequest
	(*CreateResponse)(nil), // 1: helloworld.v1.createResponse
	(*FindRequest)(nil),    // 2: helloworld.v1.findRequest
	(*FindResponse)(nil),   // 3: helloworld.v1.findResponse
}
var file_api_helloworld_v1_user_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.User.CreateUser:input_type -> helloworld.v1.createRequest
	2, // 1: helloworld.v1.User.FindUser:input_type -> helloworld.v1.findRequest
	1, // 2: helloworld.v1.User.CreateUser:output_type -> helloworld.v1.createResponse
	3, // 3: helloworld.v1.User.FindUser:output_type -> helloworld.v1.findResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_user_proto_init() }
func file_api_helloworld_v1_user_proto_init() {
	if File_api_helloworld_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_user_proto_rawDesc), len(file_api_helloworld_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_user_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_user_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_user_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_user_proto = out.File
	file_api_helloworld_v1_user_proto_goTypes = nil
	file_api_helloworld_v1_user_proto_depIdxs = nil
}
