// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/helloworld/v1/accountcustomer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountCustomer_CreateAccountCustomer_FullMethodName = "/helloworld.v1.AccountCustomer/CreateAccountCustomer"
)

// AccountCustomerClient is the client API for AccountCustomer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type AccountCustomerClient interface {
	// Sends a greeting
	CreateAccountCustomer(ctx context.Context, in *CreateCustomerAccountRequest, opts ...grpc.CallOption) (*CreateCustomerAccountReply, error)
}

type accountCustomerClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountCustomerClient(cc grpc.ClientConnInterface) AccountCustomerClient {
	return &accountCustomerClient{cc}
}

func (c *accountCustomerClient) CreateAccountCustomer(ctx context.Context, in *CreateCustomerAccountRequest, opts ...grpc.CallOption) (*CreateCustomerAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCustomerAccountReply)
	err := c.cc.Invoke(ctx, AccountCustomer_CreateAccountCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountCustomerServer is the server API for AccountCustomer service.
// All implementations must embed UnimplementedAccountCustomerServer
// for forward compatibility.
//
// The greeting service definition.
type AccountCustomerServer interface {
	// Sends a greeting
	CreateAccountCustomer(context.Context, *CreateCustomerAccountRequest) (*CreateCustomerAccountReply, error)
	mustEmbedUnimplementedAccountCustomerServer()
}

// UnimplementedAccountCustomerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountCustomerServer struct{}

func (UnimplementedAccountCustomerServer) CreateAccountCustomer(context.Context, *CreateCustomerAccountRequest) (*CreateCustomerAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountCustomer not implemented")
}
func (UnimplementedAccountCustomerServer) mustEmbedUnimplementedAccountCustomerServer() {}
func (UnimplementedAccountCustomerServer) testEmbeddedByValue()                         {}

// UnsafeAccountCustomerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountCustomerServer will
// result in compilation errors.
type UnsafeAccountCustomerServer interface {
	mustEmbedUnimplementedAccountCustomerServer()
}

func RegisterAccountCustomerServer(s grpc.ServiceRegistrar, srv AccountCustomerServer) {
	// If the following call pancis, it indicates UnimplementedAccountCustomerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountCustomer_ServiceDesc, srv)
}

func _AccountCustomer_CreateAccountCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCustomerServer).CreateAccountCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCustomer_CreateAccountCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCustomerServer).CreateAccountCustomer(ctx, req.(*CreateCustomerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountCustomer_ServiceDesc is the grpc.ServiceDesc for AccountCustomer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountCustomer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.AccountCustomer",
	HandlerType: (*AccountCustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountCustomer",
			Handler:    _AccountCustomer_CreateAccountCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/helloworld/v1/accountcustomer.proto",
}
