// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/accountcustomer.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCustomerAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerAccountRequest) Reset() {
	*x = CreateCustomerAccountRequest{}
	mi := &file_api_helloworld_v1_accountcustomer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerAccountRequest) ProtoMessage() {}

func (x *CreateCustomerAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountcustomer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountcustomer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCustomerAccountRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateCustomerAccountRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type CreateCustomerAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerAccountReply) Reset() {
	*x = CreateCustomerAccountReply{}
	mi := &file_api_helloworld_v1_accountcustomer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerAccountReply) ProtoMessage() {}

func (x *CreateCustomerAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountcustomer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerAccountReply.ProtoReflect.Descriptor instead.
func (*CreateCustomerAccountReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountcustomer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerAccountReply) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateCustomerAccountReply) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_api_helloworld_v1_accountcustomer_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_accountcustomer_proto_rawDesc = "" +
	"\n" +
	"'api/helloworld/v1/accountcustomer.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\\\n" +
	"\x1ccreateCustomerAccountRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\tR\n" +
	"customerId\"Z\n" +
	"\x1acreateCustomerAccountReply\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\tR\n" +
	"customerId2\xa9\x01\n" +
	"\x0fAccountCustomer\x12\x95\x01\n" +
	"\x15CreateAccountCustomer\x12+.helloworld.v1.createCustomerAccountRequest\x1a).helloworld.v1.createCustomerAccountReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19v1/accountcustomer/createBZ\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z%account-customer/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_accountcustomer_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_accountcustomer_proto_rawDescData []byte
)

func file_api_helloworld_v1_accountcustomer_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_accountcustomer_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_accountcustomer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_accountcustomer_proto_rawDesc), len(file_api_helloworld_v1_accountcustomer_proto_rawDesc)))
	})
	return file_api_helloworld_v1_accountcustomer_proto_rawDescData
}

var file_api_helloworld_v1_accountcustomer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_helloworld_v1_accountcustomer_proto_goTypes = []any{
	(*CreateCustomerAccountRequest)(nil), // 0: helloworld.v1.createCustomerAccountRequest
	(*CreateCustomerAccountReply)(nil),   // 1: helloworld.v1.createCustomerAccountReply
}
var file_api_helloworld_v1_accountcustomer_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.AccountCustomer.CreateAccountCustomer:input_type -> helloworld.v1.createCustomerAccountRequest
	1, // 1: helloworld.v1.AccountCustomer.CreateAccountCustomer:output_type -> helloworld.v1.createCustomerAccountReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_accountcustomer_proto_init() }
func file_api_helloworld_v1_accountcustomer_proto_init() {
	if File_api_helloworld_v1_accountcustomer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_accountcustomer_proto_rawDesc), len(file_api_helloworld_v1_accountcustomer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_accountcustomer_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_accountcustomer_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_accountcustomer_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_accountcustomer_proto = out.File
	file_api_helloworld_v1_accountcustomer_proto_goTypes = nil
	file_api_helloworld_v1_accountcustomer_proto_depIdxs = nil
}
