// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/helloworld/v1/alert.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNotificationCreateNotification = "/helloworld.v1.Notification/CreateNotification"
const OperationNotificationCreateTransactionNotification = "/helloworld.v1.Notification/CreateTransactionNotification"

type NotificationHTTPServer interface {
	// CreateNotification Sends a greeting
	CreateNotification(context.Context, *NotificationRequest) (*NotificationResponse, error)
	CreateTransactionNotification(context.Context, *TransactionRequest) (*TransactionResponse, error)
}

func RegisterNotificationHTTPServer(s *http.Server, srv NotificationHTTPServer) {
	r := s.Route("/")
	r.POST("v1/alert/otp", _Notification_CreateNotification0_HTTP_Handler(srv))
	r.POST("v1/alert/transaction", _Notification_CreateTransactionNotification0_HTTP_Handler(srv))
}

func _Notification_CreateNotification0_HTTP_Handler(srv NotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in NotificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationCreateNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNotification(ctx, req.(*NotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotificationResponse)
		return ctx.Result(200, reply)
	}
}

func _Notification_CreateTransactionNotification0_HTTP_Handler(srv NotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TransactionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationCreateTransactionNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTransactionNotification(ctx, req.(*TransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TransactionResponse)
		return ctx.Result(200, reply)
	}
}

type NotificationHTTPClient interface {
	CreateNotification(ctx context.Context, req *NotificationRequest, opts ...http.CallOption) (rsp *NotificationResponse, err error)
	CreateTransactionNotification(ctx context.Context, req *TransactionRequest, opts ...http.CallOption) (rsp *TransactionResponse, err error)
}

type NotificationHTTPClientImpl struct {
	cc *http.Client
}

func NewNotificationHTTPClient(client *http.Client) NotificationHTTPClient {
	return &NotificationHTTPClientImpl{client}
}

func (c *NotificationHTTPClientImpl) CreateNotification(ctx context.Context, in *NotificationRequest, opts ...http.CallOption) (*NotificationResponse, error) {
	var out NotificationResponse
	pattern := "v1/alert/otp"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationCreateNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationHTTPClientImpl) CreateTransactionNotification(ctx context.Context, in *TransactionRequest, opts ...http.CallOption) (*TransactionResponse, error) {
	var out TransactionResponse
	pattern := "v1/alert/transaction"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationCreateTransactionNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
