// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/alert.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           int64                  `protobuf:"varint,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetOtp() int64 {
	if x != nil {
		return x.Otp
	}
	return 0
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_alert_proto_rawDescGZIP(), []int{2}
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message1      string                 `protobuf:"bytes,1,opt,name=message1,proto3" json:"message1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_alert_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionResponse) GetMessage1() string {
	if x != nil {
		return x.Message1
	}
	return ""
}

var File_api_helloworld_v1_alert_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/helloworld/v1/alert.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"+\n" +
	"\x13NotificationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"(\n" +
	"\x14NotificationResponse\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\x03R\x03otp\"\x14\n" +
	"\x12TransactionRequest\"1\n" +
	"\x13TransactionResponse\x12\x1a\n" +
	"\bmessage1\x18\x01 \x01(\tR\bmessage12\x90\x02\n" +
	"\fNotification\x12v\n" +
	"\x12CreateNotification\x12\".helloworld.v1.NotificationRequest\x1a#.helloworld.v1.NotificationResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\fv1/alert/otp\x12\x87\x01\n" +
	"\x1dCreateTransactionNotification\x12!.helloworld.v1.TransactionRequest\x1a\".helloworld.v1.TransactionResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14v1/alert/transactionBY\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z$message-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_alert_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_alert_proto_rawDescData []byte
)

func file_api_helloworld_v1_alert_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_alert_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_alert_proto_rawDesc), len(file_api_helloworld_v1_alert_proto_rawDesc)))
	})
	return file_api_helloworld_v1_alert_proto_rawDescData
}

var file_api_helloworld_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_helloworld_v1_alert_proto_goTypes = []any{
	(*NotificationRequest)(nil),  // 0: helloworld.v1.NotificationRequest
	(*NotificationResponse)(nil), // 1: helloworld.v1.NotificationResponse
	(*TransactionRequest)(nil),   // 2: helloworld.v1.TransactionRequest
	(*TransactionResponse)(nil),  // 3: helloworld.v1.TransactionResponse
}
var file_api_helloworld_v1_alert_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Notification.CreateNotification:input_type -> helloworld.v1.NotificationRequest
	2, // 1: helloworld.v1.Notification.CreateTransactionNotification:input_type -> helloworld.v1.TransactionRequest
	1, // 2: helloworld.v1.Notification.CreateNotification:output_type -> helloworld.v1.NotificationResponse
	3, // 3: helloworld.v1.Notification.CreateTransactionNotification:output_type -> helloworld.v1.TransactionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_alert_proto_init() }
func file_api_helloworld_v1_alert_proto_init() {
	if File_api_helloworld_v1_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_alert_proto_rawDesc), len(file_api_helloworld_v1_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_alert_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_alert_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_alert_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_alert_proto = out.File
	file_api_helloworld_v1_alert_proto_goTypes = nil
	file_api_helloworld_v1_alert_proto_depIdxs = nil
}
