// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"transaction-service/internal/biz"
	"transaction-service/internal/conf"
	"transaction-service/internal/data"
	"transaction-service/internal/server"
	"transaction-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	client "transaction-service/internal/client"
	"fmt"
	
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	paymentClient, err := client.NewPaymentClient("localhost:9004") // or use confData
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create account client: %w", err)
	}
	greeterRepo := data.NewTransactionRepo(dataData, logger)
	greeterUsecase := biz.NewTransactionUsecase(greeterRepo, logger)
	greeterService := service.NewTransactionService(greeterUsecase,paymentClient)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
