// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/accountblocks.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountBlock int32

const (
	AccountBlock_UNKNOWN_BLOCK AccountBlock = 0
	AccountBlock_riskBlock     AccountBlock = 1
	AccountBlock_caseBlock     AccountBlock = 2
	AccountBlock_adminBlock    AccountBlock = 3
	AccountBlock_release       AccountBlock = 4
)

// Enum value maps for AccountBlock.
var (
	AccountBlock_name = map[int32]string{
		0: "UNKNOWN_BLOCK",
		1: "riskBlock",
		2: "caseBlock",
		3: "adminBlock",
		4: "release",
	}
	AccountBlock_value = map[string]int32{
		"UNKNOWN_BLOCK": 0,
		"riskBlock":     1,
		"caseBlock":     2,
		"adminBlock":    3,
		"release":       4,
	}
)

func (x AccountBlock) Enum() *AccountBlock {
	p := new(AccountBlock)
	*p = x
	return p
}

func (x AccountBlock) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountBlock) Descriptor() protoreflect.EnumDescriptor {
	return file_api_helloworld_v1_accountblocks_proto_enumTypes[0].Descriptor()
}

func (AccountBlock) Type() protoreflect.EnumType {
	return &file_api_helloworld_v1_accountblocks_proto_enumTypes[0]
}

func (x AccountBlock) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountBlock.Descriptor instead.
func (AccountBlock) EnumDescriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountblocks_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber int64                  `protobuf:"varint,3,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	Accblock      AccountBlock           `protobuf:"varint,2,opt,name=accblock,proto3,enum=helloworld.v1.AccountBlock" json:"accblock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountblocks_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *BlockRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *BlockRequest) GetAccblock() AccountBlock {
	if x != nil {
		return x.Accblock
	}
	return AccountBlock_UNKNOWN_BLOCK
}

// The response message containing the greetings
type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	Accblock      AccountBlock           `protobuf:"varint,3,opt,name=accblock,proto3,enum=helloworld.v1.AccountBlock" json:"accblock,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountblocks_proto_rawDescGZIP(), []int{1}
}

func (x *BlockResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *BlockResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *BlockResponse) GetAccblock() AccountBlock {
	if x != nil {
		return x.Accblock
	}
	return AccountBlock_UNKNOWN_BLOCK
}

func (x *BlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber int64                  `protobuf:"varint,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindBlockRequest) Reset() {
	*x = FindBlockRequest{}
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBlockRequest) ProtoMessage() {}

func (x *FindBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBlockRequest.ProtoReflect.Descriptor instead.
func (*FindBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountblocks_proto_rawDescGZIP(), []int{2}
}

func (x *FindBlockRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindBlockRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type FindBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber int64                  `protobuf:"varint,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	Accblock      AccountBlock           `protobuf:"varint,2,opt,name=accblock,proto3,enum=helloworld.v1.AccountBlock" json:"accblock,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AccountId     int64                  `protobuf:"varint,4,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindBlockResponse) Reset() {
	*x = FindBlockResponse{}
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBlockResponse) ProtoMessage() {}

func (x *FindBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBlockResponse.ProtoReflect.Descriptor instead.
func (*FindBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountblocks_proto_rawDescGZIP(), []int{3}
}

func (x *FindBlockResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindBlockResponse) GetAccblock() AccountBlock {
	if x != nil {
		return x.Accblock
	}
	return AccountBlock_UNKNOWN_BLOCK
}

func (x *FindBlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FindBlockResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type UpdateBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	Accblock      AccountBlock           `protobuf:"varint,3,opt,name=accblock,proto3,enum=helloworld.v1.AccountBlock" json:"accblock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlockRequest) Reset() {
	*x = UpdateBlockRequest{}
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockRequest) ProtoMessage() {}

func (x *UpdateBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountblocks_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBlockRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateBlockRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateBlockRequest) GetAccblock() AccountBlock {
	if x != nil {
		return x.Accblock
	}
	return AccountBlock_UNKNOWN_BLOCK
}

type UpdateBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	Accblock      AccountBlock           `protobuf:"varint,3,opt,name=accblock,proto3,enum=helloworld.v1.AccountBlock" json:"accblock,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlockResponse) Reset() {
	*x = UpdateBlockResponse{}
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockResponse) ProtoMessage() {}

func (x *UpdateBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_accountblocks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockResponse.ProtoReflect.Descriptor instead.
func (*UpdateBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_accountblocks_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBlockResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateBlockResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateBlockResponse) GetAccblock() AccountBlock {
	if x != nil {
		return x.Accblock
	}
	return AccountBlock_UNKNOWN_BLOCK
}

func (x *UpdateBlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_accountblocks_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_accountblocks_proto_rawDesc = "" +
	"\n" +
	"%api/helloworld/v1/accountblocks.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\x8b\x01\n" +
	"\fBlockRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x03 \x01(\x03R\raccountNumber\x127\n" +
	"\baccblock\x18\x02 \x01(\x0e2\x1b.helloworld.v1.AccountBlockR\baccblock\"\xa6\x01\n" +
	"\rBlockResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x127\n" +
	"\baccblock\x18\x03 \x01(\x0e2\x1b.helloworld.v1.AccountBlockR\baccblock\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"V\n" +
	"\x10FindBlockRequest\x12$\n" +
	"\raccountNumber\x18\x01 \x01(\x03R\raccountNumber\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\"\xaa\x01\n" +
	"\x11FindBlockResponse\x12$\n" +
	"\raccountNumber\x18\x01 \x01(\x03R\raccountNumber\x127\n" +
	"\baccblock\x18\x02 \x01(\x0e2\x1b.helloworld.v1.AccountBlockR\baccblock\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\taccountId\x18\x04 \x01(\x03R\taccountId\"\x91\x01\n" +
	"\x12UpdateBlockRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x127\n" +
	"\baccblock\x18\x03 \x01(\x0e2\x1b.helloworld.v1.AccountBlockR\baccblock\"\xac\x01\n" +
	"\x13UpdateBlockResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x127\n" +
	"\baccblock\x18\x03 \x01(\x0e2\x1b.helloworld.v1.AccountBlockR\baccblock\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*\\\n" +
	"\fAccountBlock\x12\x11\n" +
	"\rUNKNOWN_BLOCK\x10\x00\x12\r\n" +
	"\triskBlock\x10\x01\x12\r\n" +
	"\tcaseBlock\x10\x02\x12\x0e\n" +
	"\n" +
	"adminBlock\x10\x03\x12\v\n" +
	"\arelease\x10\x042\xc1\x05\n" +
	"\aGreeter\x12k\n" +
	"\x12CreateAccountBlock\x12\x1b.helloworld.v1.BlockRequest\x1a\x1c.helloworld.v1.BlockResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0fv1/accountblock\x12j\n" +
	"\x11AdminAccountBlock\x12\x1b.helloworld.v1.BlockRequest\x1a\x1c.helloworld.v1.BlockResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0fv1/accountblock\x12i\n" +
	"\x10RiskAccountBlock\x12\x1b.helloworld.v1.BlockRequest\x1a\x1c.helloworld.v1.BlockResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0fv1/accountblock\x12i\n" +
	"\x10CaseAccountBlock\x12\x1b.helloworld.v1.BlockRequest\x1a\x1c.helloworld.v1.BlockResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0fv1/accountblock\x12\x86\x01\n" +
	"\x10FindAccountBlock\x12\x1f.helloworld.v1.FindBlockRequest\x1a .helloworld.v1.FindBlockResponse\"/\x82\xd3\xe4\x93\x02):\x01*\x12$v1/find/accountblock/{accountNumber}\x12~\n" +
	"\x12UpdateAccountBlock\x12!.helloworld.v1.UpdateBlockRequest\x1a\".helloworld.v1.UpdateBlockResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16v1/update/accountblockBW\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z\"account-block/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_accountblocks_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_accountblocks_proto_rawDescData []byte
)

func file_api_helloworld_v1_accountblocks_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_accountblocks_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_accountblocks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_accountblocks_proto_rawDesc), len(file_api_helloworld_v1_accountblocks_proto_rawDesc)))
	})
	return file_api_helloworld_v1_accountblocks_proto_rawDescData
}

var file_api_helloworld_v1_accountblocks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_helloworld_v1_accountblocks_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_helloworld_v1_accountblocks_proto_goTypes = []any{
	(AccountBlock)(0),           // 0: helloworld.v1.AccountBlock
	(*BlockRequest)(nil),        // 1: helloworld.v1.BlockRequest
	(*BlockResponse)(nil),       // 2: helloworld.v1.BlockResponse
	(*FindBlockRequest)(nil),    // 3: helloworld.v1.FindBlockRequest
	(*FindBlockResponse)(nil),   // 4: helloworld.v1.FindBlockResponse
	(*UpdateBlockRequest)(nil),  // 5: helloworld.v1.UpdateBlockRequest
	(*UpdateBlockResponse)(nil), // 6: helloworld.v1.UpdateBlockResponse
}
var file_api_helloworld_v1_accountblocks_proto_depIdxs = []int32{
	0,  // 0: helloworld.v1.BlockRequest.accblock:type_name -> helloworld.v1.AccountBlock
	0,  // 1: helloworld.v1.BlockResponse.accblock:type_name -> helloworld.v1.AccountBlock
	0,  // 2: helloworld.v1.FindBlockResponse.accblock:type_name -> helloworld.v1.AccountBlock
	0,  // 3: helloworld.v1.UpdateBlockRequest.accblock:type_name -> helloworld.v1.AccountBlock
	0,  // 4: helloworld.v1.UpdateBlockResponse.accblock:type_name -> helloworld.v1.AccountBlock
	1,  // 5: helloworld.v1.Greeter.CreateAccountBlock:input_type -> helloworld.v1.BlockRequest
	1,  // 6: helloworld.v1.Greeter.AdminAccountBlock:input_type -> helloworld.v1.BlockRequest
	1,  // 7: helloworld.v1.Greeter.RiskAccountBlock:input_type -> helloworld.v1.BlockRequest
	1,  // 8: helloworld.v1.Greeter.CaseAccountBlock:input_type -> helloworld.v1.BlockRequest
	3,  // 9: helloworld.v1.Greeter.FindAccountBlock:input_type -> helloworld.v1.FindBlockRequest
	5,  // 10: helloworld.v1.Greeter.UpdateAccountBlock:input_type -> helloworld.v1.UpdateBlockRequest
	2,  // 11: helloworld.v1.Greeter.CreateAccountBlock:output_type -> helloworld.v1.BlockResponse
	2,  // 12: helloworld.v1.Greeter.AdminAccountBlock:output_type -> helloworld.v1.BlockResponse
	2,  // 13: helloworld.v1.Greeter.RiskAccountBlock:output_type -> helloworld.v1.BlockResponse
	2,  // 14: helloworld.v1.Greeter.CaseAccountBlock:output_type -> helloworld.v1.BlockResponse
	4,  // 15: helloworld.v1.Greeter.FindAccountBlock:output_type -> helloworld.v1.FindBlockResponse
	6,  // 16: helloworld.v1.Greeter.UpdateAccountBlock:output_type -> helloworld.v1.UpdateBlockResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_accountblocks_proto_init() }
func file_api_helloworld_v1_accountblocks_proto_init() {
	if File_api_helloworld_v1_accountblocks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_accountblocks_proto_rawDesc), len(file_api_helloworld_v1_accountblocks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_accountblocks_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_accountblocks_proto_depIdxs,
		EnumInfos:         file_api_helloworld_v1_accountblocks_proto_enumTypes,
		MessageInfos:      file_api_helloworld_v1_accountblocks_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_accountblocks_proto = out.File
	file_api_helloworld_v1_accountblocks_proto_goTypes = nil
	file_api_helloworld_v1_accountblocks_proto_depIdxs = nil
}
