// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	FromAccountId   int64                  `protobuf:"varint,2,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId     int64                  `protobuf:"varint,3,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	PaymentType     string                 `protobuf:"bytes,4,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,7,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Fee             string                 `protobuf:"bytes,10,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreateRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *CreateRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *CreateRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRequest) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type CreateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	FromAccountId   int64                  `protobuf:"varint,2,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId     int64                  `protobuf:"varint,3,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	PaymentType     string                 `protobuf:"bytes,4,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,7,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	Fee             string                 `protobuf:"bytes,11,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreateResponse) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *CreateResponse) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *CreateResponse) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreateResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateResponse) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type UpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	FromAccountId   int64                  `protobuf:"varint,2,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId     int64                  `protobuf:"varint,3,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	PaymentType     string                 `protobuf:"bytes,4,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,7,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *UpdateRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *UpdateRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *UpdateRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *UpdateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpdateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdateRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	FromAccountId   int64                  `protobuf:"varint,2,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId     int64                  `protobuf:"varint,3,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	PaymentType     string                 `protobuf:"bytes,4,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,7,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *UpdateResponse) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *UpdateResponse) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *UpdateResponse) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *UpdateResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpdateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdateResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *DeleteRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type DeleteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	FromAccountId   int64                  `protobuf:"varint,2,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId     int64                  `protobuf:"varint,3,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	PaymentType     string                 `protobuf:"bytes,4,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,7,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *DeleteResponse) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *DeleteResponse) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *DeleteResponse) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *DeleteResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DeleteResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeleteResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *DeleteResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *DeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	FromAccountId   int64                  `protobuf:"varint,2,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId     int64                  `protobuf:"varint,3,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	PaymentType     string                 `protobuf:"bytes,4,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,7,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *FindRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *FindRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *FindRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *FindRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *FindRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FindRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *FindRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *FindRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FindResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       int64                  `protobuf:"varint,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	FromAccountId   int64                  `protobuf:"varint,2,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId     int64                  `protobuf:"varint,3,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	PaymentType     string                 `protobuf:"bytes,4,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,7,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *FindResponse) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *FindResponse) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *FindResponse) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *FindResponse) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *FindResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FindResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *FindResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *FindResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_payment_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/payment.proto\x12\x0ehelloworld3.v1\x1a\x1cgoogle/api/annotations.proto\"\xc5\x02\n" +
	"\rcreateRequest\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12$\n" +
	"\rfromAccountId\x18\x02 \x01(\x03R\rfromAccountId\x12 \n" +
	"\vtoAccountId\x18\x03 \x01(\x03R\vtoAccountId\x12 \n" +
	"\vpaymentType\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12$\n" +
	"\rpaymentMethod\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x0freferenceNumber\x18\b \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x10\n" +
	"\x03fee\x18\n" +
	" \x01(\tR\x03fee\"\xe0\x02\n" +
	"\x0ecreateResponse\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12$\n" +
	"\rfromAccountId\x18\x02 \x01(\x03R\rfromAccountId\x12 \n" +
	"\vtoAccountId\x18\x03 \x01(\x03R\vtoAccountId\x12 \n" +
	"\vpaymentType\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12$\n" +
	"\rpaymentMethod\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x0freferenceNumber\x18\b \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\x12\x10\n" +
	"\x03fee\x18\v \x01(\tR\x03fee\"\xb3\x02\n" +
	"\rupdateRequest\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12$\n" +
	"\rfromAccountId\x18\x02 \x01(\x03R\rfromAccountId\x12 \n" +
	"\vtoAccountId\x18\x03 \x01(\x03R\vtoAccountId\x12 \n" +
	"\vpaymentType\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12$\n" +
	"\rpaymentMethod\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x0freferenceNumber\x18\b \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\xce\x02\n" +
	"\x0eupdateResponse\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12$\n" +
	"\rfromAccountId\x18\x02 \x01(\x03R\rfromAccountId\x12 \n" +
	"\vtoAccountId\x18\x03 \x01(\x03R\vtoAccountId\x12 \n" +
	"\vpaymentType\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12$\n" +
	"\rpaymentMethod\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x0freferenceNumber\x18\b \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"I\n" +
	"\rdeleteRequest\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xce\x02\n" +
	"\x0edeleteResponse\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12$\n" +
	"\rfromAccountId\x18\x02 \x01(\x03R\rfromAccountId\x12 \n" +
	"\vtoAccountId\x18\x03 \x01(\x03R\vtoAccountId\x12 \n" +
	"\vpaymentType\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12$\n" +
	"\rpaymentMethod\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x0freferenceNumber\x18\b \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"\xb1\x02\n" +
	"\vfindRequest\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12$\n" +
	"\rfromAccountId\x18\x02 \x01(\x03R\rfromAccountId\x12 \n" +
	"\vtoAccountId\x18\x03 \x01(\x03R\vtoAccountId\x12 \n" +
	"\vpaymentType\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12$\n" +
	"\rpaymentMethod\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x0freferenceNumber\x18\b \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\xcc\x02\n" +
	"\ffindResponse\x12\x1c\n" +
	"\tpaymentId\x18\x01 \x01(\x03R\tpaymentId\x12$\n" +
	"\rfromAccountId\x18\x02 \x01(\x03R\rfromAccountId\x12 \n" +
	"\vtoAccountId\x18\x03 \x01(\x03R\vtoAccountId\x12 \n" +
	"\vpaymentType\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12$\n" +
	"\rpaymentMethod\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x0freferenceNumber\x18\b \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage2\xd1\x03\n" +
	"\apayment\x12l\n" +
	"\rCreatePayment\x12\x1d.helloworld3.v1.createRequest\x1a\x1e.helloworld3.v1.createResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11v1/payment/create\x12l\n" +
	"\rUpdatePayment\x12\x1d.helloworld3.v1.updateRequest\x1a\x1e.helloworld3.v1.updateResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11v1/payment/update\x12x\n" +
	"\rDeletePayment\x12\x1d.helloworld3.v1.deleteRequest\x1a\x1e.helloworld3.v1.deleteResponse\"(\x82\xd3\xe4\x93\x02\":\x01**\x1dv1/payment/delete/{paymentId}\x12p\n" +
	"\vFindPayment\x12\x1b.helloworld3.v1.findRequest\x1a\x1c.helloworld3.v1.findResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\x12\x1bv1/payment/find/{paymentId}BY\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z$payment-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_payment_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_payment_proto_rawDescData []byte
)

func file_api_helloworld_v1_payment_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_payment_proto_rawDesc), len(file_api_helloworld_v1_payment_proto_rawDesc)))
	})
	return file_api_helloworld_v1_payment_proto_rawDescData
}

var file_api_helloworld_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_payment_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: helloworld3.v1.createRequest
	(*CreateResponse)(nil), // 1: helloworld3.v1.createResponse
	(*UpdateRequest)(nil),  // 2: helloworld3.v1.updateRequest
	(*UpdateResponse)(nil), // 3: helloworld3.v1.updateResponse
	(*DeleteRequest)(nil),  // 4: helloworld3.v1.deleteRequest
	(*DeleteResponse)(nil), // 5: helloworld3.v1.deleteResponse
	(*FindRequest)(nil),    // 6: helloworld3.v1.findRequest
	(*FindResponse)(nil),   // 7: helloworld3.v1.findResponse
}
var file_api_helloworld_v1_payment_proto_depIdxs = []int32{
	0, // 0: helloworld3.v1.payment.CreatePayment:input_type -> helloworld3.v1.createRequest
	2, // 1: helloworld3.v1.payment.UpdatePayment:input_type -> helloworld3.v1.updateRequest
	4, // 2: helloworld3.v1.payment.DeletePayment:input_type -> helloworld3.v1.deleteRequest
	6, // 3: helloworld3.v1.payment.FindPayment:input_type -> helloworld3.v1.findRequest
	1, // 4: helloworld3.v1.payment.CreatePayment:output_type -> helloworld3.v1.createResponse
	3, // 5: helloworld3.v1.payment.UpdatePayment:output_type -> helloworld3.v1.updateResponse
	5, // 6: helloworld3.v1.payment.DeletePayment:output_type -> helloworld3.v1.deleteResponse
	7, // 7: helloworld3.v1.payment.FindPayment:output_type -> helloworld3.v1.findResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_payment_proto_init() }
func file_api_helloworld_v1_payment_proto_init() {
	if File_api_helloworld_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_payment_proto_rawDesc), len(file_api_helloworld_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_payment_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_payment_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_payment_proto = out.File
	file_api_helloworld_v1_payment_proto_goTypes = nil
	file_api_helloworld_v1_payment_proto_depIdxs = nil
}
