// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/card.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CreateRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateRequest) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *CreateRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *CreateRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *CreateRequest) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *CreateRequest) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CreateResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *CreateResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *CreateResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *CreateResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *CreateResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *UpdateRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *UpdateRequest) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *UpdateRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *UpdateRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *UpdateRequest) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *UpdateRequest) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *UpdateResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *UpdateResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *UpdateResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *UpdateResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *UpdateResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *UpdateResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *DeleteRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *DeleteResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *DeleteResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *DeleteResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *DeleteResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *DeleteResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *DeleteResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *DeleteResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *DeleteResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{6}
}

func (x *FindRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *FindRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *FindResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *FindResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *FindResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *FindResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *FindResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *FindResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *FindResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

var File_api_helloworld_v1_card_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x1capi/helloworld/v1/card.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xb6\x02\n" +
	"\rcreateRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"\xb7\x02\n" +
	"\x0ecreateResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"\xb6\x02\n" +
	"\rupdateRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"\xb7\x02\n" +
	"\x0eupdateResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"O\n" +
	"\rdeleteRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\"\xb7\x02\n" +
	"\x0edeleteResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"M\n" +
	"\vfindRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\"\xb5\x02\n" +
	"\ffindResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt2\x9a\x03\n" +
	"\aGreeter\x12`\n" +
	"\n" +
	"CreateCard\x12\x1c.helloworld.v1.createRequest\x1a\x1d.helloworld.v1.createResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/create\x12_\n" +
	"\n" +
	"UpdateCard\x12\x1c.helloworld.v1.updateRequest\x1a\x1d.helloworld.v1.updateResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\tv1/update\x12i\n" +
	"\n" +
	"DeleteCard\x12\x1c.helloworld.v1.deleteRequest\x1a\x1d.helloworld.v1.deleteResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01**\x13v1/delete/{card_id}\x12a\n" +
	"\bFindCard\x12\x1a.helloworld.v1.findRequest\x1a\x1b.helloworld.v1.findResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x12\x11v1/find/{card_id}BV\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z!card-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_card_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_card_proto_rawDescData []byte
)

func file_api_helloworld_v1_card_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_card_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_card_proto_rawDesc), len(file_api_helloworld_v1_card_proto_rawDesc)))
	})
	return file_api_helloworld_v1_card_proto_rawDescData
}

var file_api_helloworld_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_card_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: helloworld.v1.createRequest
	(*CreateResponse)(nil), // 1: helloworld.v1.createResponse
	(*UpdateRequest)(nil),  // 2: helloworld.v1.updateRequest
	(*UpdateResponse)(nil), // 3: helloworld.v1.updateResponse
	(*DeleteRequest)(nil),  // 4: helloworld.v1.deleteRequest
	(*DeleteResponse)(nil), // 5: helloworld.v1.deleteResponse
	(*FindRequest)(nil),    // 6: helloworld.v1.findRequest
	(*FindResponse)(nil),   // 7: helloworld.v1.findResponse
}
var file_api_helloworld_v1_card_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Greeter.CreateCard:input_type -> helloworld.v1.createRequest
	2, // 1: helloworld.v1.Greeter.UpdateCard:input_type -> helloworld.v1.updateRequest
	4, // 2: helloworld.v1.Greeter.DeleteCard:input_type -> helloworld.v1.deleteRequest
	6, // 3: helloworld.v1.Greeter.FindCard:input_type -> helloworld.v1.findRequest
	1, // 4: helloworld.v1.Greeter.CreateCard:output_type -> helloworld.v1.createResponse
	3, // 5: helloworld.v1.Greeter.UpdateCard:output_type -> helloworld.v1.updateResponse
	5, // 6: helloworld.v1.Greeter.DeleteCard:output_type -> helloworld.v1.deleteResponse
	7, // 7: helloworld.v1.Greeter.FindCard:output_type -> helloworld.v1.findResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_card_proto_init() }
func file_api_helloworld_v1_card_proto_init() {
	if File_api_helloworld_v1_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_card_proto_rawDesc), len(file_api_helloworld_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_card_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_card_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_card_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_card_proto = out.File
	file_api_helloworld_v1_card_proto_goTypes = nil
	file_api_helloworld_v1_card_proto_depIdxs = nil
}
