// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/card.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCardRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CreateCardRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateCardRequest) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *CreateCardRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *CreateCardRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *CreateCardRequest) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *CreateCardRequest) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	Message       string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CreateCardResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateCardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateCardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateCardResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *CreateCardResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *CreateCardResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *CreateCardResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *CreateCardResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

func (x *CreateCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCardRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *UpdateCardRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *UpdateCardRequest) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *UpdateCardRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *UpdateCardRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *UpdateCardRequest) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *UpdateCardRequest) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type UpdateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	Message       string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCardResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *UpdateCardResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateCardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateCardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *UpdateCardResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *UpdateCardResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *UpdateCardResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *UpdateCardResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *UpdateCardResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

func (x *UpdateCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCardRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *DeleteCardRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	Message       string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCardResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *DeleteCardResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *DeleteCardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *DeleteCardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *DeleteCardResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *DeleteCardResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *DeleteCardResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *DeleteCardResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *DeleteCardResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

func (x *DeleteCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCardRequest) Reset() {
	*x = FindCardRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCardRequest) ProtoMessage() {}

func (x *FindCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCardRequest.ProtoReflect.Descriptor instead.
func (*FindCardRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{6}
}

func (x *FindCardRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *FindCardRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *FindCardRequest) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *FindCardRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *FindCardRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *FindCardRequest) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *FindCardRequest) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

type FindCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,5,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,7,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,8,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	PinAttempt    string                 `protobuf:"bytes,9,opt,name=pin_attempt,json=pinAttempt,proto3" json:"pin_attempt,omitempty"`
	Message       string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCardResponse) Reset() {
	*x = FindCardResponse{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCardResponse) ProtoMessage() {}

func (x *FindCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCardResponse.ProtoReflect.Descriptor instead.
func (*FindCardResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *FindCardResponse) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *FindCardResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindCardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindCardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *FindCardResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *FindCardResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *FindCardResponse) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *FindCardResponse) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *FindCardResponse) GetPinAttempt() string {
	if x != nil {
		return x.PinAttempt
	}
	return ""
}

func (x *FindCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_card_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x1capi/helloworld/v1/card.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xba\x02\n" +
	"\x11createCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"\xd5\x02\n" +
	"\x12createCardResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"\xba\x02\n" +
	"\x11updateCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"\xd5\x02\n" +
	"\x12updateCardResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"S\n" +
	"\x11deleteCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\"\xd5\x02\n" +
	"\x12deleteCardResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"\xb8\x02\n" +
	"\x0ffindCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\"\xd3\x02\n" +
	"\x10findCardResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x05 \x01(\tR\n" +
	"cardStatus\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\a \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\b \x01(\tR\fmonthlyLimit\x12\x1f\n" +
	"\vpin_attempt\x18\t \x01(\tR\n" +
	"pinAttempt\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage2\xb7\x03\n" +
	"\aGreeter\x12h\n" +
	"\n" +
	"CreateCard\x12 .helloworld.v1.createCardRequest\x1a!.helloworld.v1.createCardResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/create\x12g\n" +
	"\n" +
	"UpdateCard\x12 .helloworld.v1.updateCardRequest\x1a!.helloworld.v1.updateCardResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\tv1/update\x12q\n" +
	"\n" +
	"DeleteCard\x12 .helloworld.v1.deleteCardRequest\x1a!.helloworld.v1.deleteCardResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01**\x13v1/delete/{card_id}\x12f\n" +
	"\bFindCard\x12\x1e.helloworld.v1.findCardRequest\x1a\x1f.helloworld.v1.findCardResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11v1/find/{card_id}BV\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z!card-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_card_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_card_proto_rawDescData []byte
)

func file_api_helloworld_v1_card_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_card_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_card_proto_rawDesc), len(file_api_helloworld_v1_card_proto_rawDesc)))
	})
	return file_api_helloworld_v1_card_proto_rawDescData
}

var file_api_helloworld_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_card_proto_goTypes = []any{
	(*CreateCardRequest)(nil),  // 0: helloworld.v1.createCardRequest
	(*CreateCardResponse)(nil), // 1: helloworld.v1.createCardResponse
	(*UpdateCardRequest)(nil),  // 2: helloworld.v1.updateCardRequest
	(*UpdateCardResponse)(nil), // 3: helloworld.v1.updateCardResponse
	(*DeleteCardRequest)(nil),  // 4: helloworld.v1.deleteCardRequest
	(*DeleteCardResponse)(nil), // 5: helloworld.v1.deleteCardResponse
	(*FindCardRequest)(nil),    // 6: helloworld.v1.findCardRequest
	(*FindCardResponse)(nil),   // 7: helloworld.v1.findCardResponse
}
var file_api_helloworld_v1_card_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Greeter.CreateCard:input_type -> helloworld.v1.createCardRequest
	2, // 1: helloworld.v1.Greeter.UpdateCard:input_type -> helloworld.v1.updateCardRequest
	4, // 2: helloworld.v1.Greeter.DeleteCard:input_type -> helloworld.v1.deleteCardRequest
	6, // 3: helloworld.v1.Greeter.FindCard:input_type -> helloworld.v1.findCardRequest
	1, // 4: helloworld.v1.Greeter.CreateCard:output_type -> helloworld.v1.createCardResponse
	3, // 5: helloworld.v1.Greeter.UpdateCard:output_type -> helloworld.v1.updateCardResponse
	5, // 6: helloworld.v1.Greeter.DeleteCard:output_type -> helloworld.v1.deleteCardResponse
	7, // 7: helloworld.v1.Greeter.FindCard:output_type -> helloworld.v1.findCardResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_card_proto_init() }
func file_api_helloworld_v1_card_proto_init() {
	if File_api_helloworld_v1_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_card_proto_rawDesc), len(file_api_helloworld_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_card_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_card_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_card_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_card_proto = out.File
	file_api_helloworld_v1_card_proto_goTypes = nil
	file_api_helloworld_v1_card_proto_depIdxs = nil
}
