// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/helloworld/v1/card.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterCreateCard = "/helloworld.v1.Greeter/CreateCard"
const OperationGreeterDeleteCard = "/helloworld.v1.Greeter/DeleteCard"
const OperationGreeterFindCard = "/helloworld.v1.Greeter/FindCard"
const OperationGreeterUpdateCard = "/helloworld.v1.Greeter/UpdateCard"

type GreeterHTTPServer interface {
	CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error)
	DeleteCard(context.Context, *DeleteCardRequest) (*DeleteCardResponse, error)
	FindCard(context.Context, *FindCardRequest) (*FindCardResponse, error)
	UpdateCard(context.Context, *UpdateCardRequest) (*UpdateCardResponse, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/create", _Greeter_CreateCard0_HTTP_Handler(srv))
	r.PUT("v1/update", _Greeter_UpdateCard0_HTTP_Handler(srv))
	r.DELETE("v1/delete/{card_id}", _Greeter_DeleteCard0_HTTP_Handler(srv))
	r.GET("v1/find/{card_id}", _Greeter_FindCard0_HTTP_Handler(srv))
}

func _Greeter_CreateCard0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterCreateCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCard(ctx, req.(*CreateCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCardResponse)
		return ctx.Result(200, reply)
	}
}

func _Greeter_UpdateCard0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterUpdateCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCard(ctx, req.(*UpdateCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCardResponse)
		return ctx.Result(200, reply)
	}
}

func _Greeter_DeleteCard0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterDeleteCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCard(ctx, req.(*DeleteCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCardResponse)
		return ctx.Result(200, reply)
	}
}

func _Greeter_FindCard0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindCardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterFindCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindCard(ctx, req.(*FindCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindCardResponse)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	CreateCard(ctx context.Context, req *CreateCardRequest, opts ...http.CallOption) (rsp *CreateCardResponse, err error)
	DeleteCard(ctx context.Context, req *DeleteCardRequest, opts ...http.CallOption) (rsp *DeleteCardResponse, err error)
	FindCard(ctx context.Context, req *FindCardRequest, opts ...http.CallOption) (rsp *FindCardResponse, err error)
	UpdateCard(ctx context.Context, req *UpdateCardRequest, opts ...http.CallOption) (rsp *UpdateCardResponse, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...http.CallOption) (*CreateCardResponse, error) {
	var out CreateCardResponse
	pattern := "/v1/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterCreateCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...http.CallOption) (*DeleteCardResponse, error) {
	var out DeleteCardResponse
	pattern := "v1/delete/{card_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterDeleteCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) FindCard(ctx context.Context, in *FindCardRequest, opts ...http.CallOption) (*FindCardResponse, error) {
	var out FindCardResponse
	pattern := "v1/find/{card_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterFindCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...http.CallOption) (*UpdateCardResponse, error) {
	var out UpdateCardResponse
	pattern := "v1/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterUpdateCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
