server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
 database:
    driver: postgres
    source: postgres://santhosh.s:root@localhost:5432/financial_details?sslmode=disable

