// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"account-block/internal/conf"
	"account-block/internal/data"
	"account-block/internal/handler"
	"account-block/internal/server"
	"account-block/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	client "account-block/internal/client"
	"fmt"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountClient, err := client.NewAccountClient("localhost:9000") // or use confData
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create account client: %w", err)
	}
	greeter1:=data.NewGreeterRepo(dataData,logger)
	accountBlockHandler := handler.NewAccountHandler(greeter1)
	accountBlockServiceService := service.NewAccountBlockService(accountBlockHandler,accountClient)
	grpcServer := server.NewGRPCServer(confServer, accountBlockServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, accountBlockServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}