// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/transaction.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CreateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRequest) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *CreateRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type CreateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CreateResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateResponse) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *CreateResponse) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateResponse) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type UpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateRequest) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *UpdateRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *UpdateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpdateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdateRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type UpdateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateResponse) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *UpdateResponse) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *UpdateResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpdateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdateResponse) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type DeleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *DeleteRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteRequest) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *DeleteRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *DeleteRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DeleteRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeleteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeleteRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *DeleteRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type DeleteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *DeleteResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteResponse) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *DeleteResponse) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *DeleteResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DeleteResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeleteResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *DeleteResponse) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type FindRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *FindRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *FindRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindRequest) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *FindRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *FindRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FindRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *FindRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type FindReponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindReponse) Reset() {
	*x = FindReponse{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindReponse) ProtoMessage() {}

func (x *FindReponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindReponse.ProtoReflect.Descriptor instead.
func (*FindReponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *FindReponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *FindReponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindReponse) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *FindReponse) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *FindReponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FindReponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindReponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindReponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindReponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *FindReponse) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

var File_api_helloworld_v1_transaction_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"#api/helloworld/v1/transaction.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xd5\x02\n" +
	"\rcreateRequest\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xd6\x02\n" +
	"\x0ecreateResponse\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xd5\x02\n" +
	"\rupdateRequest\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xd6\x02\n" +
	"\x0eupdateResponse\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xd5\x02\n" +
	"\rdeleteRequest\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xd6\x02\n" +
	"\x0edeleteResponse\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xd3\x02\n" +
	"\vfindRequest\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xd3\x02\n" +
	"\vfindReponse\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate2\xc4\x03\n" +
	"\vTransaction\x12f\n" +
	"\x11CreateTransaction\x12\x1c.helloworld.v1.createRequest\x1a\x1d.helloworld.v1.createResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\tv1/create\x12f\n" +
	"\x11UpdateTransaction\x12\x1c.helloworld.v1.updateRequest\x1a\x1d.helloworld.v1.updateResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\tv1/update\x12v\n" +
	"\x11DeleteTransaction\x12\x1c.helloworld.v1.deleteRequest\x1a\x1d.helloworld.v1.deleteResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01**\x19v1/delete/{transactionId}\x12m\n" +
	"\x0fFindTransaction\x12\x1a.helloworld.v1.findRequest\x1a\x1a.helloworld.v1.findReponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x12\x17v1/find/{transactionId}B]\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z(transaction-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_transaction_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_transaction_proto_rawDescData []byte
)

func file_api_helloworld_v1_transaction_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_transaction_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_transaction_proto_rawDesc), len(file_api_helloworld_v1_transaction_proto_rawDesc)))
	})
	return file_api_helloworld_v1_transaction_proto_rawDescData
}

var file_api_helloworld_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_transaction_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: helloworld.v1.createRequest
	(*CreateResponse)(nil), // 1: helloworld.v1.createResponse
	(*UpdateRequest)(nil),  // 2: helloworld.v1.updateRequest
	(*UpdateResponse)(nil), // 3: helloworld.v1.updateResponse
	(*DeleteRequest)(nil),  // 4: helloworld.v1.deleteRequest
	(*DeleteResponse)(nil), // 5: helloworld.v1.deleteResponse
	(*FindRequest)(nil),    // 6: helloworld.v1.findRequest
	(*FindReponse)(nil),    // 7: helloworld.v1.findReponse
}
var file_api_helloworld_v1_transaction_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Transaction.CreateTransaction:input_type -> helloworld.v1.createRequest
	2, // 1: helloworld.v1.Transaction.UpdateTransaction:input_type -> helloworld.v1.updateRequest
	4, // 2: helloworld.v1.Transaction.DeleteTransaction:input_type -> helloworld.v1.deleteRequest
	6, // 3: helloworld.v1.Transaction.FindTransaction:input_type -> helloworld.v1.findRequest
	1, // 4: helloworld.v1.Transaction.CreateTransaction:output_type -> helloworld.v1.createResponse
	3, // 5: helloworld.v1.Transaction.UpdateTransaction:output_type -> helloworld.v1.updateResponse
	5, // 6: helloworld.v1.Transaction.DeleteTransaction:output_type -> helloworld.v1.deleteResponse
	7, // 7: helloworld.v1.Transaction.FindTransaction:output_type -> helloworld.v1.findReponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_transaction_proto_init() }
func file_api_helloworld_v1_transaction_proto_init() {
	if File_api_helloworld_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_transaction_proto_rawDesc), len(file_api_helloworld_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_transaction_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_transaction_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_transaction_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_transaction_proto = out.File
	file_api_helloworld_v1_transaction_proto_goTypes = nil
	file_api_helloworld_v1_transaction_proto_depIdxs = nil
}
