// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/transaction.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequestTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRequestTransaction) Reset() {
	*x = CreateRequestTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestTransaction) ProtoMessage() {}

func (x *CreateRequestTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestTransaction.ProtoReflect.Descriptor instead.
func (*CreateRequestTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequestTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CreateRequestTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRequestTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *CreateRequestTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateRequestTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateRequestTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRequestTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRequestTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequestTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateRequestTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type CreateResponseTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	Message         string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateResponseTransaction) Reset() {
	*x = CreateResponseTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponseTransaction) ProtoMessage() {}

func (x *CreateResponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponseTransaction.ProtoReflect.Descriptor instead.
func (*CreateResponseTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponseTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CreateResponseTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateResponseTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *CreateResponseTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateResponseTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateResponseTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateResponseTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateResponseTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateResponseTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateResponseTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *CreateResponseTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRequestTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRequestTransaction) Reset() {
	*x = UpdateRequestTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestTransaction) ProtoMessage() {}

func (x *UpdateRequestTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestTransaction.ProtoReflect.Descriptor instead.
func (*UpdateRequestTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequestTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateRequestTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateRequestTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *UpdateRequestTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *UpdateRequestTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpdateRequestTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRequestTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRequestTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRequestTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdateRequestTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type UpdateResponseTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	Message         string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateResponseTransaction) Reset() {
	*x = UpdateResponseTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponseTransaction) ProtoMessage() {}

func (x *UpdateResponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponseTransaction.ProtoReflect.Descriptor instead.
func (*UpdateResponseTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponseTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateResponseTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateResponseTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *UpdateResponseTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *UpdateResponseTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpdateResponseTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateResponseTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateResponseTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateResponseTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdateResponseTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *UpdateResponseTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRequestTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRequestTransaction) Reset() {
	*x = DeleteRequestTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequestTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequestTransaction) ProtoMessage() {}

func (x *DeleteRequestTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequestTransaction.ProtoReflect.Descriptor instead.
func (*DeleteRequestTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequestTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *DeleteRequestTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteRequestTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *DeleteRequestTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *DeleteRequestTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DeleteRequestTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeleteRequestTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteRequestTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeleteRequestTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *DeleteRequestTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type DeleteResponseTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	Message         string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteResponseTransaction) Reset() {
	*x = DeleteResponseTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponseTransaction) ProtoMessage() {}

func (x *DeleteResponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponseTransaction.ProtoReflect.Descriptor instead.
func (*DeleteResponseTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponseTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *DeleteResponseTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteResponseTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *DeleteResponseTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *DeleteResponseTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DeleteResponseTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeleteResponseTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteResponseTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeleteResponseTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *DeleteResponseTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *DeleteResponseTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindRequestTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindRequestTransaction) Reset() {
	*x = FindRequestTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequestTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequestTransaction) ProtoMessage() {}

func (x *FindRequestTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequestTransaction.ProtoReflect.Descriptor instead.
func (*FindRequestTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *FindRequestTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *FindRequestTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindRequestTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *FindRequestTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *FindRequestTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FindRequestTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindRequestTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindRequestTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindRequestTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *FindRequestTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type FindReponseTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RelatedId       int64                  `protobuf:"varint,3,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=referenceNumber,proto3" json:"referenceNumber,omitempty"`
	PostingDate     string                 `protobuf:"bytes,10,opt,name=postingDate,proto3" json:"postingDate,omitempty"`
	Message         string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindReponseTransaction) Reset() {
	*x = FindReponseTransaction{}
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindReponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindReponseTransaction) ProtoMessage() {}

func (x *FindReponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindReponseTransaction.ProtoReflect.Descriptor instead.
func (*FindReponseTransaction) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *FindReponseTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *FindReponseTransaction) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindReponseTransaction) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *FindReponseTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *FindReponseTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FindReponseTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindReponseTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindReponseTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindReponseTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *FindReponseTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *FindReponseTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_transaction_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"#api/helloworld/v1/transaction.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xe0\x02\n" +
	"\x18createRequestTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xfb\x02\n" +
	"\x19createResponseTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\"\xe0\x02\n" +
	"\x18updateRequestTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xfb\x02\n" +
	"\x19updateResponseTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\"\xe0\x02\n" +
	"\x18deleteRequestTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xfb\x02\n" +
	"\x19deleteResponseTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\"\xde\x02\n" +
	"\x16findRequestTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\"\xf8\x02\n" +
	"\x16findReponseTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\x03R\rtransactionId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1c\n" +
	"\trelatedId\x18\x03 \x01(\x03R\trelatedId\x12(\n" +
	"\x0ftransactionType\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x0freferenceNumber\x18\t \x01(\tR\x0freferenceNumber\x12 \n" +
	"\vpostingDate\x18\n" +
	" \x01(\tR\vpostingDate\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage2\xd0\x04\n" +
	"\vTransaction\x12\x88\x01\n" +
	"\x11CreateTransaction\x12'.helloworld.v1.createRequestTransaction\x1a(.helloworld.v1.createResponseTransaction\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15v1/transaction/create\x12\x88\x01\n" +
	"\x11UpdateTransaction\x12'.helloworld.v1.updateRequestTransaction\x1a(.helloworld.v1.updateResponseTransaction\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15v1/transaction/update\x12\x98\x01\n" +
	"\x11DeleteTransaction\x12'.helloworld.v1.deleteRequestTransaction\x1a(.helloworld.v1.deleteResponseTransaction\"0\x82\xd3\xe4\x93\x02*:\x01**%v1/transaction/delete/{transactionId}\x12\x8f\x01\n" +
	"\x0fFindTransaction\x12%.helloworld.v1.findRequestTransaction\x1a%.helloworld.v1.findReponseTransaction\".\x82\xd3\xe4\x93\x02(:\x01*\x12#v1/transaction/find/{transactionId}B]\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z(transaction-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_transaction_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_transaction_proto_rawDescData []byte
)

func file_api_helloworld_v1_transaction_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_transaction_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_transaction_proto_rawDesc), len(file_api_helloworld_v1_transaction_proto_rawDesc)))
	})
	return file_api_helloworld_v1_transaction_proto_rawDescData
}

var file_api_helloworld_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_transaction_proto_goTypes = []any{
	(*CreateRequestTransaction)(nil),  // 0: helloworld.v1.createRequestTransaction
	(*CreateResponseTransaction)(nil), // 1: helloworld.v1.createResponseTransaction
	(*UpdateRequestTransaction)(nil),  // 2: helloworld.v1.updateRequestTransaction
	(*UpdateResponseTransaction)(nil), // 3: helloworld.v1.updateResponseTransaction
	(*DeleteRequestTransaction)(nil),  // 4: helloworld.v1.deleteRequestTransaction
	(*DeleteResponseTransaction)(nil), // 5: helloworld.v1.deleteResponseTransaction
	(*FindRequestTransaction)(nil),    // 6: helloworld.v1.findRequestTransaction
	(*FindReponseTransaction)(nil),    // 7: helloworld.v1.findReponseTransaction
}
var file_api_helloworld_v1_transaction_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Transaction.CreateTransaction:input_type -> helloworld.v1.createRequestTransaction
	2, // 1: helloworld.v1.Transaction.UpdateTransaction:input_type -> helloworld.v1.updateRequestTransaction
	4, // 2: helloworld.v1.Transaction.DeleteTransaction:input_type -> helloworld.v1.deleteRequestTransaction
	6, // 3: helloworld.v1.Transaction.FindTransaction:input_type -> helloworld.v1.findRequestTransaction
	1, // 4: helloworld.v1.Transaction.CreateTransaction:output_type -> helloworld.v1.createResponseTransaction
	3, // 5: helloworld.v1.Transaction.UpdateTransaction:output_type -> helloworld.v1.updateResponseTransaction
	5, // 6: helloworld.v1.Transaction.DeleteTransaction:output_type -> helloworld.v1.deleteResponseTransaction
	7, // 7: helloworld.v1.Transaction.FindTransaction:output_type -> helloworld.v1.findReponseTransaction
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_transaction_proto_init() }
func file_api_helloworld_v1_transaction_proto_init() {
	if File_api_helloworld_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_transaction_proto_rawDesc), len(file_api_helloworld_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_transaction_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_transaction_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_transaction_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_transaction_proto = out.File
	file_api_helloworld_v1_transaction_proto_goTypes = nil
	file_api_helloworld_v1_transaction_proto_depIdxs = nil
}
