// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: helloworld/v1/rule.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomerId       int64                  `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,3,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuleRequest) Reset() {
	*x = RuleRequest{}
	mi := &file_helloworld_v1_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleRequest) ProtoMessage() {}

func (x *RuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleRequest.ProtoReflect.Descriptor instead.
func (*RuleRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_rule_proto_rawDescGZIP(), []int{0}
}

func (x *RuleRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *RuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

type RuleResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomerId       int64                  `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,3,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuleResponse) Reset() {
	*x = RuleResponse{}
	mi := &file_helloworld_v1_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleResponse) ProtoMessage() {}

func (x *RuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleResponse.ProtoReflect.Descriptor instead.
func (*RuleResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_rule_proto_rawDescGZIP(), []int{1}
}

func (x *RuleResponse) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *RuleResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

var File_helloworld_v1_rule_proto protoreflect.FileDescriptor

const file_helloworld_v1_rule_proto_rawDesc = "" +
	"\n" +
	"\x18helloworld/v1/rule.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"{\n" +
	"\vRuleRequest\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\x03R\n" +
	"customerId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x10availableBalance\x18\x03 \x01(\tR\x10availableBalance\"|\n" +
	"\fRuleResponse\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\x03R\n" +
	"customerId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x10availableBalance\x18\x03 \x01(\tR\x10availableBalance2P\n" +
	"\aGreeter\x12E\n" +
	"\n" +
	"RuleEngine\x12\x1a.helloworld.v1.RuleRequest\x1a\x1b.helloworld.v1.RuleResponseBV\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z!rule-engine1/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_rule_proto_rawDescOnce sync.Once
	file_helloworld_v1_rule_proto_rawDescData []byte
)

func file_helloworld_v1_rule_proto_rawDescGZIP() []byte {
	file_helloworld_v1_rule_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_rule_proto_rawDesc), len(file_helloworld_v1_rule_proto_rawDesc)))
	})
	return file_helloworld_v1_rule_proto_rawDescData
}

var file_helloworld_v1_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helloworld_v1_rule_proto_goTypes = []any{
	(*RuleRequest)(nil),  // 0: helloworld.v1.RuleRequest
	(*RuleResponse)(nil), // 1: helloworld.v1.RuleResponse
}
var file_helloworld_v1_rule_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Greeter.RuleEngine:input_type -> helloworld.v1.RuleRequest
	1, // 1: helloworld.v1.Greeter.RuleEngine:output_type -> helloworld.v1.RuleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_rule_proto_init() }
func file_helloworld_v1_rule_proto_init() {
	if File_helloworld_v1_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_rule_proto_rawDesc), len(file_helloworld_v1_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_rule_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_rule_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_rule_proto_msgTypes,
	}.Build()
	File_helloworld_v1_rule_proto = out.File
	file_helloworld_v1_rule_proto_goTypes = nil
	file_helloworld_v1_rule_proto_depIdxs = nil
}
